### PR TITLE
Refactor java role

### PR DESCRIPTION
**Pull request by manics**
Use `_` in variable names
Control JDK installation with a boolean instead of requiring a list of versions, since it probably makes sense for this to be the same as the JRE versions

--rebased-from https://github.com/openmicroscopy/infrastructure/pull/219

### CODE REVIEW

**Comment by joshmoore** [comment]
Now that we've separated the repositories out, this PR brings up the question of what build(s)/job(s)/repo(s) should test it? How do we know that it will be consumable (other than manually)?

**Comment by manics** [comment]
I'm currently investigating [Molecule](https://molecule.readthedocs.io/) but for now you'll have to test it by bumping the requirements in https://github.com/openmicroscopy/infrastructure and running vagrant manually.

**Comment by manics** [comment]
@joshmoore I've replaced the old tests with molecule, see the updated `.travis.yml`, can be tested with docker or vagrant.

**Comment by joshmoore** [comment]
Wow. Ok. Re-reviewing. Thanks.

**Comment by joshmoore** [comment]
Molecule output looks good. Merging and releasing as 2.0.0.

**Pull request merged**
