### PR TITLE
Molecule V2, support Ubuntu 18.04

### PR DESCRIPTION
**Pull request by manics**
Updates test to molecule V2.
Adds support for Ubuntu 18.04.

I've put the two platforms in separate scenarios to reduce the resources required for testing.

### CODE REVIEW

**Comment by manics** [comment]
At the moment this is backwards compatible, but I think it'd be better to change `java_jre_versions` from the three digit format `1.8.0` to use the current Java versioning system i.e. just `8`. Thoughts?

**Comment by sbesson** [comment]
Generally:

- :+1: for the upgrade to `molecule 2`
- :+1: for adding Ubuntu 18.04 support and testing

Re the scenario strategy, this departs from what was proposed in https://github.com/ome/ansible-roles/issues/3 but overall we need to gain experience on the usage of these scenarios. I assume `molecule test --all` will run all scenarios serially, what does the default `molecule test` command do?

Re Java version, is the main goal to simplify the computation of the Ubuntu packages to be installed? What is the cost of maintaining backwards compatibility i.e. accept `8` but parse `1.8.0` internally?

**Comment by manics** [comment]
We could parse `1.8.0` but for maintainability I think it's better to keep things simple and only support one format. I'm happy to add an error check though, similar to what we did with postgres when we changed the variables.

If there's no `default` scenario `molecule test` returns an error.

**Comment by sbesson** [comment]
Merging to include the Molecule v2 improvements. We can review the scenarios decision down the line. The breaking switch to a different format for `java_jre_versions` can be proposed and discussed in a dedicated PR.

**Pull request merged**
